### ISSUE TITLE
Wrong prop tally results and status

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/spacebox-writer#11]
```sql=
select * from spacebox.proposal_tally_result final 
where proposal_id = 155
```

the trigger suppose to be in the [endblocker](https://docs.cosmos.network/main/modules/gov#endblocker)

**Comment by malekvictor** [comment]
Issue moved to [bro-n-bro/spacebox-crawler #33](https://github.com/bro-n-bro/spacebox-crawler/issues/33) via [**Zenhub**](https://www.zenhub.com/)
