### ISSUE TITLE
Add MsgWithdrawValidatorCommission table

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/spacebox-writer#18]
```sql=
height int 
tx_hash str
msg_index int 
withdraw_commission int
senderAddress str
```

index on tx_hash, msg_index

[hint](https://docs.cosmos.network/v0.47/modules/distribution#msgwithdrawvalidatorcommission)

**Comment by MihasBel** [comment]
type WithdrawValidatorCommissionMessage struct {
	Height             int64  `json:"height"`
	TxHash             string `json:"tx_hash"`
	MsgIndex           int64  `json:"msg_index"`
	WithdrawCommission int64  `json:"withdraw_commission"`
	WithdrawCommission Coins  `json:"withdraw_commission"`
	ValidatorAddress   string `json:"validator_address"`
}
