### ISSUE TITLE
Add MsgSubmitProposal table 

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/spacebox-writer#26]
```sql=
height int
tx_hash str
msg_index int 
proposer str
messages str
initial_deposit int
metadata str
title str
summary str
```

index on tx_hash, msg_index

**Comment by MihasBel** [comment]
package model

type SubmitProposalMessage struct {
	Height         int64  `json:"height"`
	TxHash         string `json:"tx_hash"`
	MsgIndex       int64  `json:"msg_index"`
	Proposer       string `json:"proposer"`
	InitialDeposit Coins  `json:"initial_deposit"`
	Title          string `json:"title"`
	Description    string `json:"description"`
	Type           string `json:"type"`
	ProposalID     uint64 `json:"proposal_id"`
}
