### ISSUE TITLE
Add MsgVoteWeighted table 

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/spacebox-writer#27]
```sql=
height int
tx_hash str
msg_index int
proposal_id int
voter str
WeightedVoteOption str
```

index on tx_hash, msg_index

**Comment by MihasBel** [comment]
type VoteWeightedMessage struct {
	Height             int64                `json:"height"`
	TxHash             string               `json:"tx_hash"`
	MsgIndex           int64                `json:"msg_index"`
	ProposalId         uint64               `json:"proposal_id"`
	Voter              string               `json:"voter"`
	WeightedVoteOption []WeightedVoteOption `json:"weighted_vote_option"`
}

type WeightedVoteOption struct {
	Option int32   `json:"option,omitempty"`
	Weight float64 `json:"weight"`
}
